# Generated by Django 3.0.4 on 2020-04-11 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=300)),
                ('phone', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('bio', models.CharField(default='', max_length=3000)),
                ('vehicle', models.CharField(default='', max_length=3000)),
                ('dob', models.CharField(default='', max_length=100)),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=300)),
                ('phone', models.IntegerField(default=0)),
                ('aadhar', models.IntegerField(default=0)),
                ('mechanic_id', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('ratings', models.IntegerField(default=0)),
                ('expertat', models.CharField(default='', max_length=1000)),
                ('avg_amt', models.IntegerField(default=0)),
                ('bio', models.CharField(default='', max_length=3000)),
                ('dob', models.CharField(default='', max_length=100)),
                ('mymechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
