# Generated by Django 3.0.4 on 2020-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200412_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic_accounts',
            name='Experience',
            field=models.CharField(default='Beginner', max_length=100),
        ),
    ]
