# Generated by Django 3.0.4 on 2020-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mechanic_accounts_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('mechanic_name', models.CharField(default='', max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('satisfied', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
