# Generated by Django 3.0.4 on 2020-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200422_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic_accounts',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
