# Generated by Django 3.0.4 on 2020-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200427_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='model',
            field=models.CharField(default='', max_length=300),
        ),
    ]
