# Generated by Django 3.0.4 on 2020-05-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_accounts_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic_accounts',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/'),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/'),
        ),
    ]
