# Generated by Django 3.0.4 on 2020-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200514_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic_accounts',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/-*'),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='image',
            field=models.FileField(default='', upload_to='shop/images/'),
        ),
    ]
