# Generated by Django 3.0.4 on 2020-05-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200514_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic_accounts',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/'),
        ),
    ]
