# Generated by Django 3.0.4 on 2020-05-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200514_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_accounts',
            name='image',
            field=models.ImageField(default='/media/shop/images/bangle1.JPG', upload_to='shop/images/'),
        ),
    ]
