# Generated by Django 3.0.4 on 2020-04-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200411_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_history',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_json', models.CharField(default='', max_length=1000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
