# Generated by Django 3.0.4 on 2020-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='mail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
